import React from 'react'
import localFont from 'next/font/local'
import './globals.css'

export const metadata = {
  title: 'Insight Dashboard',
  description: 'Generated by create next app',
}

const myFont = localFont({
  src: [
    {
      path: '../public/fonts/SFUIDisplay-Semibold.otf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/SFUIDisplay-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/SFUIDisplay-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/SFUIDisplay-Light.ttf',
      weight: '300',
      style: 'normal',
    },
  ],
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  )
}
